---
title: "Individuals in Experiment 1"
author: "erin"
date: "11/17/2014"
output: html_document
---

```{r}
## load required packages
library(ggplot2)
source("~/opt/r_helper_scripts/bootsSummary.r")

## load exp1 data
intensifiers = read.table("intensifiers.tsv", header=T, sep="\t")
intensifiers = subset(intensifiers, workerid < 40) #later workers are for later experiments
intensifiers$workerid = as.factor(intensifiers$workerid)
intensifiers = intensifiers[,c("price", "intensifier", "item", "workerid")]
library(plyr)
intensifiers = ddply(intensifiers, .(workerid), transform, zprice=scale(price))
intensifiers = ddply(intensifiers, .(workerid, item), transform, zzprice=scale(price))

intensifiers = intensifiers[!is.na(intensifiers$zzprice),]
intensifiers = intensifiers[intensifiers$intensifier != "",] #don't include no intensifier in the analysis, but do use it to zscore.
## ngrams
ngrams = read.table("ngrams.sep", header=T, sep="\t")
frequency = ngrams$frequency
names(frequency) = ngrams$ngram
syllables = ngrams$syllables
names(syllables) = ngrams$ngram
total_1grams = 1024908267229
intensifiers$frequency = sapply(as.character(intensifiers$intensifier), function(adverb) {
  frequency[[adverb]]
})
intensifiers$probability = intensifiers$frequency / total_1grams
intensifiers$surprisal = - log(intensifiers$probability)
intensifiers$syllables = sapply(as.character(intensifiers$intensifier), function(adverb) {
  if (adverb == "") {
    return(0)
  } else {
    return(syllables[[adverb]])
  }
})
```

There's a huge amount of variety in people's responses.

```{r fig.width=19, fig.height=12}
p = ggplot(intensifiers, aes(x=surprisal, y=price, colour=item)) +
  geom_point() +
  geom_smooth(method="lm", se=T) +
  facet_wrap(~ workerid, scales="free_y") +
  theme_bw(28)
print(p)
```

If we z-score by participant, there's still a lot variation between items.

```{r fig.width=19, fig.height=12}
p = ggplot(intensifiers, aes(x=surprisal, y=zprice, colour=item)) +
  geom_point() +
  geom_smooth(method="lm", se=T) +
  facet_wrap(~ workerid) +
  theme_bw(28)
print(p)
```

If we z-score by both participant and item, things start to look more stable.

```{r fig.width=19, fig.height=12}
p = ggplot(intensifiers, aes(x=surprisal, y=zzprice, colour=syllables)) +
  geom_point() +
  geom_smooth(method="lm", se=T, colour="black") +
  facet_wrap(~ workerid) +
  theme_bw(28)
print(p)
```

Averaging these values across participants, there appears to be a trend of surpisal indicating higher responses.

```{r fig.width=10, fig.height=6}
intensifiers_summary = bootsSummary(data=intensifiers, measurevar="zzprice", groupvars=c("intensifier", "syllables", "surprisal"))
p = ggplot(intensifiers_summary, aes(x=surprisal, y=zzprice, colour=syllables)) +
  geom_point() +
  geom_smooth(method="lm", se=T, colour="black") +
  geom_errorbar(aes(ymin=bootsci_low, ymax=bootsci_high, x=surprisal)) +
  theme_bw(28)
print(p)
```