---
title: "mixed-effects-exp1"
author: "erin"
date: "11/17/2014"
output: html_document
---

```{r}
## load required packages
library(lme4)

## load required packages
library(ggplot2)
source("~/opt/r_helper_scripts/bootsSummary.r")

## load exp1 data
intensifiers = read.table("intensifiers.tsv", header=T, sep="\t")
intensifiers = subset(intensifiers, workerid < 40) #later workers are for later experiments
intensifiers$workerid = as.factor(intensifiers$workerid)
intensifiers = intensifiers[,c("price", "intensifier", "item", "workerid")]
library(plyr)
intensifiers = ddply(intensifiers, .(workerid), transform, zprice=scale(price))
intensifiers = ddply(intensifiers, .(workerid, item), transform, zzprice=scale(price))

intensifiers = intensifiers[!is.na(intensifiers$zzprice),]
intensifiers = intensifiers[intensifiers$intensifier != "",] #don't include no intensifier in the analysis, but do use it to zscore.
## ngrams
ngrams = read.table("ngrams.sep", header=T, sep="\t")
frequency = ngrams$frequency
names(frequency) = ngrams$ngram
syllables = ngrams$syllables
names(syllables) = ngrams$ngram
total_1grams = 1024908267229
intensifiers$frequency = sapply(as.character(intensifiers$intensifier), function(adverb) {
  frequency[[adverb]]
})
intensifiers$probability = intensifiers$frequency / total_1grams
intensifiers$surprisal = - log(intensifiers$probability)
intensifiers$syllables = sapply(as.character(intensifiers$intensifier), function(adverb) {
  if (adverb == "") {
    return(0)
  } else {
    return(syllables[[adverb]])
  }
})
```

```{r}
fm1 = lmer(price ~ 1surprisal + syllables + (1 | workerid) + (1 | item), intensifiers)
```